name = "emonav"
main = "_worker.js"
compatibility_date = "2026-03-22"

[[kv_namespaces]]
binding = "EMONAV_SESSIONS"
id = "97e4daf877a7463e820c4137fbdb3132"

[assets]
directory = "."
binding = "ASSETS"
